"""Staff Table

Revision ID: aa3c77438c4c
Revises: c9b70fc6ce75
Create Date: 2020-07-30 10:34:25.731083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3c77438c4c'
down_revision = 'c9b70fc6ce75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.Column('hostname', sa.String(length=32), nullable=True),
    sa.Column('method', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_hostname'), 'staff', ['hostname'], unique=True)
    op.create_index(op.f('ix_staff_ip'), 'staff', ['ip'], unique=True)
    op.create_index(op.f('ix_staff_mac'), 'staff', ['mac'], unique=True)
    op.create_index(op.f('ix_staff_method'), 'staff', ['method'], unique=False)
    op.create_index(op.f('ix_staff_name'), 'staff', ['name'], unique=True)
    op.create_index(op.f('ix_staff_staff_id'), 'staff', ['staff_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_staff_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_name'), table_name='staff')
    op.drop_index(op.f('ix_staff_method'), table_name='staff')
    op.drop_index(op.f('ix_staff_mac'), table_name='staff')
    op.drop_index(op.f('ix_staff_ip'), table_name='staff')
    op.drop_index(op.f('ix_staff_hostname'), table_name='staff')
    op.drop_table('staff')
    # ### end Alembic commands ###
